### ISSUE TITLE
Download of larger plots throws a 400

### ISSUE THREAD

**Issue by OverBrave** [IntellectualSites/Arkitektonika#12]
```
[23:06:51 INFO]: Over_Brave issued server command: /plot download
[23:06:52 ERROR]: [PlotSquared/PlotUploader] Failed to upload schematic
java.util.concurrent.CompletionException: com.plotsquared.core.arkitektonika.exceptions.InvalidFormatException: Failed to upload '/upload'. Code: 400 (Bad Request). Reason: Uploaded file is not of valid NBT format
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: com.plotsquared.core.arkitektonika.exceptions.InvalidFormatException: Failed to upload '/upload'. Code: 400 (Bad Request). Reason: Uploaded file is not of valid NBT format
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$4(ApiClient.java:85) ~[PlotSquared-Bukkit-6.0.8-Premium.jar:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient$$Lambda$8032/0x000000000c0a5b90.accept(Unknown Source) ~[PlotSquared-Bukkit-6.0.8-Premium.jar:?]
        at com.plotsquared.core.http.HttpClient$WrappedRequestBuilder.execute(HttpClient.java:333) ~[PlotSquared-Bukkit-6.0.8-Premium.jar:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$7(ApiClient.java:90) ~[PlotSquared-Bukkit-6.0.8-Premium.jar:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient$$Lambda$8028/0x000000000c09fe90.get(Unknown Source) ~[PlotSquared-Bukkit-6.0.8-Premium.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
```
Schematic:
[test.zip](https://github.com/IntellectualSites/Arkitektonika/files/7012510/test.zip)

If I try it on an empty plot, it gives me the download link without any problem.

/plot debug
https://athion.net/ISPaster/paste/view/b97e6f1d8e7643bd89d993b233b224f1

**Comment by NotMyFault** [comment]
The 400 is likely out of place here but refers to the cap. I attempted to download a plot sized 505 blocks today and received the same bad result.

**Comment by OverBrave** [comment]
@NotMyFault, whats the latest status? Its been almots 1 years 😅

**Comment by NotMyFault** [comment]
> @NotMyFault, whats the latest status? Its been almots 1 years 😅

I'm not a maintainer of this project, @PierreSchwang started a rewrite some time ago but I am not aware of its status at the moment.

**Comment by TeamNoxious** [comment]
Was there ever a fix for this? Im still getting this issue on the latest version PlotSquared v6 6.10.6. Getting 

```
Failed to upload schematic
java.util.concurrent.CompletionException: com.plotsquared.core.arkitektonika.exceptions.ResourceUploadException: Failed to upload '/upload'. Code: 502 (Bad Gateway). Reason: Other
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.plotsquared.core.arkitektonika.exceptions.ResourceUploadException: Failed to upload '/upload'. Code: 502 (Bad Gateway). Reason: Other
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$6(ApiClient.java:89) ~[?:?]
        at com.plotsquared.core.http.HttpClient$WrappedRequestBuilder.execute(HttpClient.java:333) ~[?:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$7(ApiClient.java:90) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

**Comment by NotMyFault** [comment]
As you can see in the exception itself, the error code is different, therefore this is a different issue you are experiencing.

**Comment by TeamNoxious** [comment]
Any idea what might be causing it? Does it on any plot even empty ones.
