### ISSUE TITLE
502 Gateway timeout

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/Arkitektonika#80]
Was there ever a fix for this? Im still getting this issue on the latest version PlotSquared v6 6.10.6. Running Spigot version 1.19.2 with bungeecord 1.19.2. Getting the following error:

```
Failed to upload schematic
java.util.concurrent.CompletionException: com.plotsquared.core.arkitektonika.exceptions.ResourceUploadException: Failed to upload '/upload'. Code: 502 (Bad Gateway). Reason: Other
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.plotsquared.core.arkitektonika.exceptions.ResourceUploadException: Failed to upload '/upload'. Code: 502 (Bad Gateway). Reason: Other
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$6(ApiClient.java:89) ~[?:?]
        at com.plotsquared.core.http.HttpClient$WrappedRequestBuilder.execute(HttpClient.java:333) ~[?:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$7(ApiClient.java:90) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

_Originally posted by @TeamNoxious in https://github.com/IntellectualSites/Arkitektonika/issues/12#issuecomment-1399875912_

**Comment by NotMyFault** [comment]
@dordsor21 Can you check whether it's running or not?

**Comment by dordsor21** [comment]
It was not

**Comment by NotMyFault** [comment]
Oh, thanks for investigating!

**Comment by shunueda** [comment]
Hey @dordsor21, looks like the server is down again. I'm seeing 502 for https://api.schematic.cloud/. Thanks in advance!

**Comment by dordsor21** [comment]
Can't be used much... Must have been down for a couple weeks
